version: '3.8'

services:
  app:
    image: timurrakhimzhan/nu-ww:latest
    networks:
      - nu-ww-network
    ports:
      - "80:3000"
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./certs:/home/node/app/certs
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_SCHEDULE=* * * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  nu-ww-network:
    name: nu-ww-network